provider:
  name: faas
  provider: faas
  gateway: http://localhost:8080

functions:
  twitter-video-url:
    lang: Dockerfile
    handler: ./
    image: zaherg/faas-twitter-video-url:0.1
    environment:
      content_type: text/html

